language: java
sudo: false

jdk:
  - oraclejdk8
  - openjdk8

script:
  - ./mvnw verify -B -P run-its -DtestSrc=remote
  - ./mvnw site -B

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: $TRAVIS_BUILD_DIR/target/site
    on:
      repo: lqc/spotbugs-maven-plugin
      branch: master
      jdk: oraclejdk8
      condition: "!$TRAVIS_PULL_REQUEST"
